import { BoardSpace, ChanceCard, DeedCard } from "@/types/game";

// Thai Monopoly Board - 40 spaces
export const THAI_BOARD: BoardSpace[] = [
  {
    id: 0,
    name: "เริ่มต้น (Start)",
    type: "start",
  },
  {
    id: 1,
    name: "กรุงเทพฯ",
    type: "city",
    color: "#8B4513",
    property: {
      id: 1,
      name: "กรุงเทพฯ",
      price: 600,
      rent: 20,
      rentWithHouse1: 100,
      rentWithHouse2: 300,
      rentWithHouse3: 900,
      rentWithHouse4: 1600,
      rentWithHotel: 2500,
      housePrice: 500,
      color: "#8B4513",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 2,
    name: "โอกาส (Chance)",
    type: "chance",
  },
  {
    id: 3,
    name: "นครปฐม",
    type: "city",
    color: "#8B4513",
    property: {
      id: 3,
      name: "นครปฐม",
      price: 600,
      rent: 40,
      rentWithHouse1: 200,
      rentWithHouse2: 600,
      rentWithHouse3: 1800,
      rentWithHouse4: 3200,
      rentWithHotel: 4500,
      housePrice: 500,
      color: "#8B4513",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 4,
    name: "ภาษีเงินได้",
    type: "tax",
    price: 2000,
  },
  {
    id: 5,
    name: "สถานีรถไฟหัวลำโพง",
    type: "station",
    price: 2000,
    rent: 250,
  },
  {
    id: 6,
    name: "ตลาดโบ๊เบ๊",
    type: "city",
    color: "#87CEEB",
    property: {
      id: 6,
      name: "ตลาดโบ๊เบ๊",
      price: 1000,
      rent: 60,
      rentWithHouse1: 300,
      rentWithHouse2: 900,
      rentWithHouse3: 2700,
      rentWithHouse4: 4000,
      rentWithHotel: 5500,
      housePrice: 500,
      color: "#87CEEB",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 7,
    name: "โอกาส (Chance)",
    type: "chance",
  },
  {
    id: 8,
    name: "เยาวราช",
    type: "city",
    color: "#87CEEB",
    property: {
      id: 8,
      name: "เยาวราช",
      price: 1000,
      rent: 60,
      rentWithHouse1: 300,
      rentWithHouse2: 900,
      rentWithHouse3: 2700,
      rentWithHouse4: 4000,
      rentWithHotel: 5500,
      housePrice: 500,
      color: "#87CEEB",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 9,
    name: "จันทบุรี",
    type: "city",
    color: "#87CEEB",
    property: {
      id: 9,
      name: "จันทบุรี",
      price: 1200,
      rent: 80,
      rentWithHouse1: 400,
      rentWithHouse2: 1000,
      rentWithHouse3: 3000,
      rentWithHouse4: 4500,
      rentWithHotel: 6000,
      housePrice: 500,
      color: "#87CEEB",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 10,
    name: "เยี่ยมเยียนคุก (Just Visiting)",
    type: "jail",
  },
  {
    id: 11,
    name: "กาญจนบุรี",
    type: "city",
    color: "#FF69B4",
    property: {
      id: 11,
      name: "กาญจนบุรี",
      price: 1400,
      rent: 100,
      rentWithHouse1: 500,
      rentWithHouse2: 1500,
      rentWithHouse3: 4500,
      rentWithHouse4: 6250,
      rentWithHotel: 7500,
      housePrice: 1000,
      color: "#FF69B4",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 12,
    name: "การไฟฟ้า",
    type: "utility",
    price: 1500,
    rent: 300,
  },
  {
    id: 13,
    name: "ระยอง",
    type: "city",
    color: "#FF69B4",
    property: {
      id: 13,
      name: "ระยอง",
      price: 1400,
      rent: 100,
      rentWithHouse1: 500,
      rentWithHouse2: 1500,
      rentWithHouse3: 4500,
      rentWithHouse4: 6250,
      rentWithHotel: 7500,
      housePrice: 1000,
      color: "#FF69B4",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 14,
    name: "สุโขทัย",
    type: "city",
    color: "#FF69B4",
    property: {
      id: 14,
      name: "สุโขทัย",
      price: 1600,
      rent: 120,
      rentWithHouse1: 600,
      rentWithHouse2: 1800,
      rentWithHouse3: 5000,
      rentWithHouse4: 7000,
      rentWithHotel: 9000,
      housePrice: 1000,
      color: "#FF69B4",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 15,
    name: "สถานีรถไฟดอนเมือง",
    type: "station",
    price: 2000,
    rent: 250,
  },
  {
    id: 16,
    name: "ภูเก็ต",
    type: "city",
    color: "#FFA500",
    property: {
      id: 16,
      name: "ภูเก็ต",
      price: 1800,
      rent: 140,
      rentWithHouse1: 700,
      rentWithHouse2: 2000,
      rentWithHouse3: 5500,
      rentWithHouse4: 7500,
      rentWithHotel: 9500,
      housePrice: 1000,
      color: "#FFA500",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 17,
    name: "โอกาส (Chance)",
    type: "chance",
  },
  {
    id: 18,
    name: "สุราษฎร์ธานี",
    type: "city",
    color: "#FFA500",
    property: {
      id: 18,
      name: "สุราษฎร์ธานี",
      price: 1800,
      rent: 140,
      rentWithHouse1: 700,
      rentWithHouse2: 2000,
      rentWithHouse3: 5500,
      rentWithHouse4: 7500,
      rentWithHotel: 9500,
      housePrice: 1000,
      color: "#FFA500",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 19,
    name: "สงขลา",
    type: "city",
    color: "#FFA500",
    property: {
      id: 19,
      name: "สงขลา",
      price: 2000,
      rent: 160,
      rentWithHouse1: 800,
      rentWithHouse2: 2200,
      rentWithHouse3: 6000,
      rentWithHouse4: 8000,
      rentWithHotel: 10000,
      housePrice: 1000,
      color: "#FFA500",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 20,
    name: "จอดฟรี (Free Parking)",
    type: "free",
  },
  {
    id: 21,
    name: "เพชรบุรี",
    type: "city",
    color: "#FF0000",
    property: {
      id: 21,
      name: "เพชรบุรี",
      price: 2200,
      rent: 180,
      rentWithHouse1: 900,
      rentWithHouse2: 2500,
      rentWithHouse3: 7000,
      rentWithHouse4: 8750,
      rentWithHotel: 10500,
      housePrice: 1500,
      color: "#FF0000",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 22,
    name: "โอกาส (Chance)",
    type: "chance",
  },
  {
    id: 23,
    name: "เชียงใหม่",
    type: "city",
    color: "#FF0000",
    property: {
      id: 23,
      name: "เชียงใหม่",
      price: 2200,
      rent: 180,
      rentWithHouse1: 900,
      rentWithHouse2: 2500,
      rentWithHouse3: 7000,
      rentWithHouse4: 8750,
      rentWithHotel: 10500,
      housePrice: 1500,
      color: "#FF0000",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 24,
    name: "การประปา",
    type: "utility",
    price: 1500,
    rent: 300,
  },
  {
    id: 25,
    name: "เชียงราย",
    type: "city",
    color: "#FF0000",
    property: {
      id: 25,
      name: "เชียงราย",
      price: 2400,
      rent: 200,
      rentWithHouse1: 1000,
      rentWithHouse2: 2500,
      rentWithHouse3: 7500,
      rentWithHouse4: 9250,
      rentWithHotel: 11000,
      housePrice: 1500,
      color: "#FF0000",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 26,
    name: "สถานีรถไฟหาดใหญ่",
    type: "station",
    price: 2000,
    rent: 250,
  },
  {
    id: 27,
    name: "แม่ฮ่องสอน",
    type: "city",
    color: "#FFFF00",
    property: {
      id: 27,
      name: "แม่ฮ่องสอน",
      price: 2600,
      rent: 220,
      rentWithHouse1: 1100,
      rentWithHouse2: 3300,
      rentWithHouse3: 8000,
      rentWithHouse4: 9750,
      rentWithHotel: 11500,
      housePrice: 1500,
      color: "#FFFF00",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 28,
    name: "ลำปาง",
    type: "city",
    color: "#FFFF00",
    property: {
      id: 28,
      name: "ลำปาง",
      price: 2600,
      rent: 220,
      rentWithHouse1: 1100,
      rentWithHouse2: 3300,
      rentWithHouse3: 8000,
      rentWithHouse4: 9750,
      rentWithHotel: 11500,
      housePrice: 1500,
      color: "#FFFF00",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 29,
    name: "โอกาส (Chance)",
    type: "chance",
  },
  {
    id: 30,
    name: "ไปคุก (Go to Jail)",
    type: "gotoJail",
  },
  {
    id: 31,
    name: "โคราช",
    type: "city",
    color: "#00FF00",
    property: {
      id: 31,
      name: "โคราช",
      price: 2800,
      rent: 220,
      rentWithHouse1: 1200,
      rentWithHouse2: 3600,
      rentWithHouse3: 8500,
      rentWithHouse4: 10250,
      rentWithHotel: 12000,
      housePrice: 1500,
      color: "#00FF00",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 32,
    name: "แดนเนรมิต",
    type: "city",
    color: "#00FF00",
    property: {
      id: 32,
      name: "แดนเนรมิต",
      price: 2800,
      rent: 260,
      rentWithHouse1: 1300,
      rentWithHouse2: 3900,
      rentWithHouse3: 9000,
      rentWithHouse4: 11000,
      rentWithHotel: 12750,
      housePrice: 2000,
      color: "#00FF00",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 33,
    name: "โอกาส (Chance)",
    type: "chance",
  },
  {
    id: 34,
    name: "สุรินทร์",
    type: "city",
    color: "#00FF00",
    property: {
      id: 34,
      name: "สุรินทร์",
      price: 3000,
      rent: 260,
      rentWithHouse1: 1300,
      rentWithHouse2: 3900,
      rentWithHouse3: 9000,
      rentWithHouse4: 11000,
      rentWithHotel: 12750,
      housePrice: 2000,
      color: "#00FF00",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 35,
    name: "สถานีรถไฟเชียงใหม่",
    type: "station",
    price: 2000,
    rent: 250,
  },
  {
    id: 36,
    name: "โอกาส (Chance)",
    type: "chance",
  },
  {
    id: 37,
    name: "อุบลราชธานี",
    type: "city",
    color: "#0000FF",
    property: {
      id: 37,
      name: "อุบลราชธานี",
      price: 3200,
      rent: 280,
      rentWithHouse1: 1500,
      rentWithHouse2: 4500,
      rentWithHouse3: 10000,
      rentWithHouse4: 12000,
      rentWithHotel: 14000,
      housePrice: 2000,
      color: "#0000FF",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
  {
    id: 38,
    name: "ภาษีหรู",
    type: "tax",
    price: 1000,
  },
  {
    id: 39,
    name: "ดอนเมือง",
    type: "city",
    color: "#0000FF",
    property: {
      id: 39,
      name: "ดอนเมือง",
      price: 3500,
      rent: 350,
      rentWithHouse1: 1750,
      rentWithHouse2: 5000,
      rentWithHouse3: 11000,
      rentWithHouse4: 13000,
      rentWithHotel: 15000,
      housePrice: 2000,
      color: "#0000FF",
      houses: 0,
      hasHotel: false,
      owner: null,
    },
  },
];

// Chance cards in Thai
export const CHANCE_CARDS: ChanceCard[] = [
  { id: 1, text: "ถูกหวย! ได้เงิน 2000 บาท", type: "money", amount: 2000 },
  { id: 2, text: "จ่ายค่าปรับความเร็ว 500 บาท", type: "money", amount: -500 },
  { id: 3, text: "เดินไปช่อง START และรับเงิน 2000 บาท", type: "move", position: 0 },
  { id: 4, text: "ไปคุกโดยตรง!", type: "jail" },
  { id: 5, text: "ออกจากคุกฟรี 1 ครั้ง", type: "jail", isGetOutOfJail: true },
  { id: 6, text: "ย้อนกลับ 3 ช่อง", type: "move", amount: -3 },
  { id: 7, text: "ได้เงินจากธนาคาร 1500 บาท", type: "money", amount: 1500 },
  { id: 8, text: "จ่ายค่าซ่อมบ้าน: บ้านละ 250 บาท, โรงแรมละ 1000 บาท", type: "repair" },
  { id: 9, text: "วันเกิด! ทุกคนให้เงินคุณคนละ 100 บาท", type: "money", amount: 0 },
  { id: 10, text: "ไปเชียงใหม่", type: "move", position: 18 },
  { id: 11, text: "ไปภูเก็ต", type: "move", position: 13 },
  { id: 12, text: "รับเงินปันผล 500 บาท", type: "money", amount: 500 },
  { id: 13, text: "เดินหน้า 5 ช่อง", type: "move", amount: 5 },
  { id: 14, text: "จ่ายภาษีที่ดิน 1000 บาท", type: "money", amount: -1000 },
  { id: 15, text: "ไปสถานีรถไฟที่ใกล้ที่สุด", type: "move", position: -1 },
];

// Helper function to get property color groups
export const getPropertyColorGroups = (): Record<string, BoardSpace[]> => {
  const groups: Record<string, BoardSpace[]> = {};
  
  THAI_BOARD.forEach((space) => {
    if (space.type === "city" && space.color) {
      if (!groups[space.color]) {
        groups[space.color] = [];
      }
      groups[space.color].push(space);
    }
  });
  
  return groups;
};

// Helper to check if player owns all properties in a color group
export const hasMonopoly = (playerId: string, color: string, properties: DeedCard[]): boolean => {
  const colorGroup = THAI_BOARD.filter(space => space.type === "city" && space.color === color);
  const playerProperties = properties.filter(p => p.owner === playerId && p.color === color);
  return colorGroup.length === playerProperties.length;
};
